run-name: Module Tests
on: [push, pull_request]
jobs:
  checkout:
    steps:
      - uses: actions/checkout@v3
  mapparser-test:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - run: python3 ./tests/test_mapparser.py